In [38]:
import pandas as pd

In [39]:
df = pd.read_csv("price.csv")
df

Town  Area   Price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      robbinsville  2600  575000
6      robbinsville  2900  600000
7      robbinsville  3100  620000
8      robbinsville  3600  695000
9      west windsor  2600  585000
10     west windsor  2800  615000
11     west windsor  3300  650000
12     west windsor  3600  710000

In [40]:
dummies = pd.get_dummies(df.Town)
dummies

monroe township  robbinsville  west windsor
0              True         False         False
1              True         False         False
2              True         False         False
3              True         False         False
4              True         False         False
5             False          True         False
6             False          True         False
7             False          True         False
8             False          True         False
9             False         False          True
10            False         False          True
11            False         False          True
12            False         False          True

In [41]:
merged = pd.concat([df, dummies], axis="columns")
merged

Town  Area   Price  monroe township  robbinsville  west windsor
0   monroe township  2600  550000             True         False         False
1   monroe township  3000  565000             True         False         False
2   monroe township  3200  610000             True         False         False
3   monroe township  3600  680000             True         False         False
4   monroe township  4000  725000             True         False         False
5      robbinsville  2600  575000            False          True         False
6      robbinsville  2900  600000            False          True         False
7      robbinsville  3100  620000            False          True         False
8      robbinsville  3600  695000            False          True         False
9      west windsor  2600  585000            False         False          True
10     west windsor  2800  615000            False         False          True
11     west windsor  3300  650000            False         False          True
12     west windsor  3600  710000            False         False          True

drop some columns which has no use

In [42]:
final = merged.drop(['Town', 'west windsor'], axis='columns')
final

Area   Price  monroe township  robbinsville
0   2600  550000             True         False
1   3000  565000             True         False
2   3200  610000             True         False
3   3600  680000             True         False
4   4000  725000             True         False
5   2600  575000            False          True
6   2900  600000            False          True
7   3100  620000            False          True
8   3600  695000            False          True
9   2600  585000            False         False
10  2800  615000            False         False
11  3300  650000            False         False
12  3600  710000            False         False

Making LinearRegression Model

In [43]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [44]:
X = final.drop(['Price'], axis=1)
X

Area  monroe township  robbinsville
0   2600             True         False
1   3000             True         False
2   3200             True         False
3   3600             True         False
4   4000             True         False
5   2600            False          True
6   2900            False          True
7   3100            False          True
8   3600            False          True
9   2600            False         False
10  2800            False         False
11  3300            False         False
12  3600            False         False

In [45]:
y = final.Price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     575000
6     600000
7     620000
8     695000
9     585000
10    615000
11    650000
12    710000
Name: Price, dtype: int64

In [46]:
model.fit(X, y)

LinearRegression()

In [47]:
model.predict([[2600, 0, 1], [2600, 1, 0]])

c:\Users\sanjo.SANJOG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([565396.15136531, 539709.7398409 ])

check the accuracy of our model

In [48]:
model.score(X, y)

0.9573929037221873

labeling the df(data frame)

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [50]:
dfle = df
dfle.Town = le.fit_transform(dfle.Town)
dfle

Town  Area   Price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      1  2600  575000
6      1  2900  600000
7      1  3100  620000
8      1  3600  695000
9      2  2600  585000
10     2  2800  615000
11     2  3300  650000
12     2  3600  710000

In [51]:
X = dfle[['Town', 'Area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600]], dtype=int64)

In [52]:
y = dfle.Price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     575000
6     600000
7     620000
8     695000
9     585000
10    615000
11    650000
12    710000
Name: Price, dtype: int64

OneHotEncoder is not running properly for my current version, so leave it as it is

In [53]:
# from sklearn.preprocessing import OneHotEncoder
# ohe = OneHotEncoder()

In [54]:
# X = ohe.fit_transform(X).toarray()
# X

GPT shows me how to do it, but it is not as like as tutorial which I see

In [55]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array([['A', 1], ['B', 2], ['A', 3]])

ohe = OneHotEncoder()

transformed_data = ohe.fit_transform(data[:, 0].reshape(-1, 1)).toarray()

print(transformed_data)


[[1. 0.]
 [0. 1.]
 [1. 0.]]
